/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSolicitudesRouteImport } from './routes/_app/solicitudes'
import { Route as AppSeguimientoRouteImport } from './routes/_app/seguimiento'
import { Route as AppInspeccionesRouteImport } from './routes/_app/inspecciones'
import { Route as AppDesembolsosRouteImport } from './routes/_app/desembolsos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAprobacionesRouteImport } from './routes/_app/aprobaciones'
import { Route as AppAnalisisRouteImport } from './routes/_app/analisis'
import { Route as AppExpedienteRouteImport } from './routes/_app/expediente.'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSolicitudesRoute = AppSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguimientoRoute = AppSeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => AppRoute,
} as any)
const AppInspeccionesRoute = AppInspeccionesRouteImport.update({
  id: '/inspecciones',
  path: '/inspecciones',
  getParentRoute: () => AppRoute,
} as any)
const AppDesembolsosRoute = AppDesembolsosRouteImport.update({
  id: '/desembolsos',
  path: '/desembolsos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAprobacionesRoute = AppAprobacionesRouteImport.update({
  id: '/aprobaciones',
  path: '/aprobaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalisisRoute = AppAnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => AppRoute,
} as any)
const AppExpedienteRoute = AppExpedienteRouteImport.update({
  id: '/expediente/',
  path: '/expediente/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analisis': typeof AppAnalisisRoute
  '/aprobaciones': typeof AppAprobacionesRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/desembolsos': typeof AppDesembolsosRoute
  '/inspecciones': typeof AppInspeccionesRoute
  '/seguimiento': typeof AppSeguimientoRoute
  '/solicitudes': typeof AppSolicitudesRoute
  '/expediente/': typeof AppExpedienteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analisis': typeof AppAnalisisRoute
  '/aprobaciones': typeof AppAprobacionesRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/desembolsos': typeof AppDesembolsosRoute
  '/inspecciones': typeof AppInspeccionesRoute
  '/seguimiento': typeof AppSeguimientoRoute
  '/solicitudes': typeof AppSolicitudesRoute
  '/expediente': typeof AppExpedienteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analisis': typeof AppAnalisisRoute
  '/_app/aprobaciones': typeof AppAprobacionesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/desembolsos': typeof AppDesembolsosRoute
  '/_app/inspecciones': typeof AppInspeccionesRoute
  '/_app/seguimiento': typeof AppSeguimientoRoute
  '/_app/solicitudes': typeof AppSolicitudesRoute
  '/_app/expediente/': typeof AppExpedienteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analisis'
    | '/aprobaciones'
    | '/clientes'
    | '/dashboard'
    | '/desembolsos'
    | '/inspecciones'
    | '/seguimiento'
    | '/solicitudes'
    | '/expediente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analisis'
    | '/aprobaciones'
    | '/clientes'
    | '/dashboard'
    | '/desembolsos'
    | '/inspecciones'
    | '/seguimiento'
    | '/solicitudes'
    | '/expediente'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analisis'
    | '/_app/aprobaciones'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/desembolsos'
    | '/_app/inspecciones'
    | '/_app/seguimiento'
    | '/_app/solicitudes'
    | '/_app/expediente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/solicitudes': {
      id: '/_app/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AppSolicitudesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguimiento': {
      id: '/_app/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof AppSeguimientoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspecciones': {
      id: '/_app/inspecciones'
      path: '/inspecciones'
      fullPath: '/inspecciones'
      preLoaderRoute: typeof AppInspeccionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desembolsos': {
      id: '/_app/desembolsos'
      path: '/desembolsos'
      fullPath: '/desembolsos'
      preLoaderRoute: typeof AppDesembolsosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aprobaciones': {
      id: '/_app/aprobaciones'
      path: '/aprobaciones'
      fullPath: '/aprobaciones'
      preLoaderRoute: typeof AppAprobacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analisis': {
      id: '/_app/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AppAnalisisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expediente/': {
      id: '/_app/expediente/'
      path: '/expediente'
      fullPath: '/expediente/'
      preLoaderRoute: typeof AppExpedienteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalisisRoute: typeof AppAnalisisRoute
  AppAprobacionesRoute: typeof AppAprobacionesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDesembolsosRoute: typeof AppDesembolsosRoute
  AppInspeccionesRoute: typeof AppInspeccionesRoute
  AppSeguimientoRoute: typeof AppSeguimientoRoute
  AppSolicitudesRoute: typeof AppSolicitudesRoute
  AppExpedienteRoute: typeof AppExpedienteRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalisisRoute: AppAnalisisRoute,
  AppAprobacionesRoute: AppAprobacionesRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDesembolsosRoute: AppDesembolsosRoute,
  AppInspeccionesRoute: AppInspeccionesRoute,
  AppSeguimientoRoute: AppSeguimientoRoute,
  AppSolicitudesRoute: AppSolicitudesRoute,
  AppExpedienteRoute: AppExpedienteRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
